// Generated by node scripts/build-offline.mjs. Do not edit directly.
const VERSION = "c4202ade4b1960ec";
const ASSETS = [
  {
    "url": "./assets/audio/quiz.mp3",
    "integrity": "sha256-LSRgQHaR2lHwakmYaP55UTyWkz5vkPYOuGd1/h5Le+4=",
    "bytes": 4800000
  },
  {
    "url": "./assets/css/style.css",
    "integrity": "sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=",
    "bytes": 0
  },
  {
    "url": "./assets/fonts/Orbitron-VariableFont_wght.ttf",
    "integrity": "sha256-Ru78cIT9mr/9h1R8R/cptgccf3qNWvKBJmuwnlRhxDU=",
    "bytes": 38548
  },
  {
    "url": "./assets/img/BSLAT/table1.png",
    "integrity": "sha256-iI1XhJmp2XKVJo8JfjcJUXQzxPK8QRcryPTmKWz3PEQ=",
    "bytes": 524799
  },
  {
    "url": "./assets/img/BSLAT/table2.png",
    "integrity": "sha256-u71Df7+IhoH8NztmXabsiadszi1AkuxpTg2wiFQ9rHs=",
    "bytes": 704365
  },
  {
    "url": "./assets/img/BSLAT/table3.png",
    "integrity": "sha256-3PGAjTclSY5DcWdwstDP3M7gg1rZcwo9yM4YwtCZJOU=",
    "bytes": 372511
  },
  {
    "url": "./assets/img/Button.svg",
    "integrity": "sha256-76JlDiVaMilIwIvPHOdoax3pid+1+2Z9vzIu8aw4ZQw=",
    "bytes": 5814
  },
  {
    "url": "./assets/img/CAABP/caaabp.png",
    "integrity": "sha256-kL3jkTNQlaVkzcTnWYuxcsoCOtlvuQyHX6tkus42gHM=",
    "bytes": 609493
  },
  {
    "url": "./assets/img/CAABP/moc.png",
    "integrity": "sha256-5W+VxePo2PpUnYMw8095k00/fjESH3XOY608owiXiL8=",
    "bytes": 50875
  },
  {
    "url": "./assets/img/CAS/law.png",
    "integrity": "sha256-TSez+ted/NWSq9shC/GvdBWiIoKZSyMx0hrmb78J//A=",
    "bytes": 707686
  },
  {
    "url": "./assets/img/CAS/sla.png",
    "integrity": "sha256-hKlzGRWOFGYDWL45AR6vkZHEGos4UPpDSYc+pA2bvK8=",
    "bytes": 765149
  },
  {
    "url": "./assets/img/CBS/cbankservice.png",
    "integrity": "sha256-NtwPj8yJWJvvuuyy161XGs9pLASDHwK5dDG3KD9H1jo=",
    "bytes": 257560
  },
  {
    "url": "./assets/img/CBS/icon1.png",
    "integrity": "sha256-FcozcESTYqI6sZveBvQy491nhQbf5S9tQDYjbpW9uJo=",
    "bytes": 45663
  },
  {
    "url": "./assets/img/CBS/icon2.png",
    "integrity": "sha256-7OhdSKWmtHC36IOzIUnhQQWxswFUixCv966x39ebGY4=",
    "bytes": 49009
  },
  {
    "url": "./assets/img/CBS/icon3.png",
    "integrity": "sha256-Jie6qlTTMPu6USROHEETfycSHEdrZ0LOEQXCNYZVYiU=",
    "bytes": 43574
  },
  {
    "url": "./assets/img/CMD/table-1.png",
    "integrity": "sha256-33cehvPF7SB9HZ7847qsV5y+IkTOk04NO5ZFIyqbM2M=",
    "bytes": 774663
  },
  {
    "url": "./assets/img/CMD/table-2.png",
    "integrity": "sha256-DKFWVuP4HIB5ywyHDEz6ufF1wVjMp7N/62ahPvOSja4=",
    "bytes": 772825
  },
  {
    "url": "./assets/img/CMD/table.png",
    "integrity": "sha256-8swYY/WOorHJy56/Q31inx5vqBdgkBWJ2pgKr5OsvdU=",
    "bytes": 765435
  },
  {
    "url": "./assets/img/Circle.svg",
    "integrity": "sha256-q83/kGNwW+NU5Xyis2Yos/UprKhhEgy4fugZiXiDYrE=",
    "bytes": 12808
  },
  {
    "url": "./assets/img/ETIBI/earth.png",
    "integrity": "sha256-+gkq/6MG3l4okzu6z57cxpS0w57ZzliHF1mH2Xi5l+w=",
    "bytes": 191817
  },
  {
    "url": "./assets/img/FMDD/market-financial-infrastructure/table-1.png",
    "integrity": "sha256-fa0+BAKPIFE9s9/QwRtl8o9AVA3IGtAp4z/u+Il9Ook=",
    "bytes": 645808
  },
  {
    "url": "./assets/img/FMDD/market-financial-infrastructure/table-2.png",
    "integrity": "sha256-eRko1r8I5Z3zk81QoChGzml7KCMi5TXwnSq3HjtmKLs=",
    "bytes": 673129
  },
  {
    "url": "./assets/img/FMDD/market-financial-infrastructure/table.png",
    "integrity": "sha256-uLVKV72fXdZiuBGoPt1gclCER1KB+z4n/H2O37k9Ix0=",
    "bytes": 654113
  },
  {
    "url": "./assets/img/FMDD/puva-derivative/table-1.png",
    "integrity": "sha256-H9Dm9Z1pZL6T0284shwfU2mB5a+Ca63+rZOq1dLeaPE=",
    "bytes": 681024
  },
  {
    "url": "./assets/img/FMDD/puva-derivative/table-2.png",
    "integrity": "sha256-K6AwA+VeaztgN9w5Rb3ZllUwCZetZcQ5C+bkCEuAsU4=",
    "bytes": 707963
  },
  {
    "url": "./assets/img/FMDD/puva-derivative/table-3.png",
    "integrity": "sha256-f4dFHoxT0HOkEJTgOGMdkZKeWF6h8ltcElCDJhcet1s=",
    "bytes": 602299
  },
  {
    "url": "./assets/img/FMDD/puva-derivative/table-4.png",
    "integrity": "sha256-ZhQTd3xit+CzvEySPLTCFq+ySX9aikM94G0kRPrr/c4=",
    "bytes": 499998
  },
  {
    "url": "./assets/img/FMDD/puva-derivative/table.png",
    "integrity": "sha256-lbaZyNAW8+CWUzEhIBaigLFZ9zyuFMdtL8ro3E0tulI=",
    "bytes": 730948
  },
  {
    "url": "./assets/img/FMDD/puva-vastra/table-1.png",
    "integrity": "sha256-nF5wtqjxxtgoJNrEGGQY7pWBqCFbSo1JQHzwcStFLmg=",
    "bytes": 219819
  },
  {
    "url": "./assets/img/FMDD/puva-vastra/table.png",
    "integrity": "sha256-R/83Sx5duCk5GmCqr8C7Pxx7Tgz2MYxEDKFaw/OaXE4=",
    "bytes": 614896
  },
  {
    "url": "./assets/img/FMDD/table1.png",
    "integrity": "sha256-7K08wSo6vhc2o6XayMuLj3rOa8Im0Af6Zzy/B61Ou/g=",
    "bytes": 730581
  },
  {
    "url": "./assets/img/FMDD/table2.png",
    "integrity": "sha256-VmcdtsdPUXl45LhG9NN20txdmO3TnOKdz+J4EaxDbos=",
    "bytes": 852336
  },
  {
    "url": "./assets/img/FMDD/table3.png",
    "integrity": "sha256-zazHJzC+5M7gs07HCqiDObo+BYQdvTbO7+/wKijGWQI=",
    "bytes": 918520
  },
  {
    "url": "./assets/img/FMDD/table4.png",
    "integrity": "sha256-FC2y64yuMbCI/Cg9s7B3SgFqay0tuFz+BcRe7thG/2Q=",
    "bytes": 878970
  },
  {
    "url": "./assets/img/FMDD/table5.png",
    "integrity": "sha256-mCgjmRRvXoaeRsRvjgehGJPzzalkmntVMQevoPIzE4Y=",
    "bytes": 1048624
  },
  {
    "url": "./assets/img/FMDD/terminology-notes/table-1.png",
    "integrity": "sha256-z3+hdOxshxySwv0MMA/Z+mnvvgtIZQIhiefJ6WeYAvo=",
    "bytes": 521234
  },
  {
    "url": "./assets/img/FMDD/terminology-notes/table-2.png",
    "integrity": "sha256-d0DiTAPXhAKEd5qyi0Tx4jRLOREj+PbZWEporZ7/Arc=",
    "bytes": 327119
  },
  {
    "url": "./assets/img/FMDD/terminology-notes/table.png",
    "integrity": "sha256-n75Qyq4/Zh94F1kpCaB3wjEfRsE75daFtY1cQFg4okk=",
    "bytes": 516161
  },
  {
    "url": "./assets/img/Frame%2015.png",
    "integrity": "sha256-m+rl/SDp28vkSaWZ6c9+RtTALRlQwo9ps7GvSbPp+XY=",
    "bytes": 442830
  },
  {
    "url": "./assets/img/GM/GM.png",
    "integrity": "sha256-J42haYGK7A0RIHGqCM2AkzMqL5Ovh6R6ZSBoFXWqTJM=",
    "bytes": 1042387
  },
  {
    "url": "./assets/img/GM/GM.svg",
    "integrity": "sha256-NaygWc5ndOukxfFjzCH8gPXw60nWaW7rM1H7d/7GKM8=",
    "bytes": 8300785
  },
  {
    "url": "./assets/img/IEFD/table.png",
    "integrity": "sha256-Bt+y+g4rm8p3eDXX9Po8q2z8QlYsYzVbYJXfEKyE2OQ=",
    "bytes": 333449
  },
  {
    "url": "./assets/img/KV.jpg",
    "integrity": "sha256-JIZ7kG3P+NVfdPXcbvNdHuj5KOZzehz7ZEM2WAUVqR4=",
    "bytes": 3304849
  },
  {
    "url": "./assets/img/LCIBP/lcibp.png",
    "integrity": "sha256-viHiC2e5A7FNB2a6ZCoH3mTD8x5rElXP782JsYY/fUQ=",
    "bytes": 517116
  },
  {
    "url": "./assets/img/LCIBP/notes.png",
    "integrity": "sha256-6p6NMMyKECDlTYb+FyoeUqH22vgU5+yKYJJrqJHYTOc=",
    "bytes": 78790
  },
  {
    "url": "./assets/img/LCTS/Tangan.png",
    "integrity": "sha256-hJ6pdVxoiN9jD0CCOT80YxGwujzctZeEeKn7QV7sUyQ=",
    "bytes": 76029
  },
  {
    "url": "./assets/img/LCTS/hand.png",
    "integrity": "sha256-A7KTy8uXdGAo+9T09MDYcHzTNQmnauV9PHOlUlCO5Ic=",
    "bytes": 478921
  },
  {
    "url": "./assets/img/LCTS/lcts.png",
    "integrity": "sha256-IXEiZ7ZdVMP05r3DbZugSppMm1CbD/t2+utAVUb7NTM=",
    "bytes": 539831
  },
  {
    "url": "./assets/img/LF/ABF.png",
    "integrity": "sha256-mTvicEiulJKddbp2g03g2D9vbRlwtISLiS8xfeDK5R0=",
    "bytes": 9242
  },
  {
    "url": "./assets/img/LF/EGI.png",
    "integrity": "sha256-IeQfGqFF9tXR1Y+DdCAEBDQl8xguO8FnY2E+ULJy1S8=",
    "bytes": 71001
  },
  {
    "url": "./assets/img/LF/Information.png",
    "integrity": "sha256-BkReUETDKQDx7RqVgFirgKEbqatCwuF/BeCrwpAGyjw=",
    "bytes": 8928
  },
  {
    "url": "./assets/img/LF/framework.png",
    "integrity": "sha256-copU/qBGNJoPJwZqsKEBHobtVDzUiFD+g15bLci3wM0=",
    "bytes": 4310082
  },
  {
    "url": "./assets/img/LF/licensing.png",
    "integrity": "sha256-L3KVuhPdWy898onlytxTB5vT7RCeyzllwdilEgeq+kk=",
    "bytes": 12446
  },
  {
    "url": "./assets/img/MASMD/table-2.png",
    "integrity": "sha256-Z2fPI8xAfm77/CxM72gIsM15/yWWVXgsyEoag+mk25o=",
    "bytes": 525168
  },
  {
    "url": "./assets/img/MASMD/table.png",
    "integrity": "sha256-HFdPLAl8f7fhE0yHT3J1m918GIcw+oKqcGs22AX8yRQ=",
    "bytes": 763620
  },
  {
    "url": "./assets/img/MMAMSD/table.png",
    "integrity": "sha256-nLmd68q38ceT9dIkkLJzNJfc+jyIXIkbXDWDUbxgTBI=",
    "bytes": 255576
  },
  {
    "url": "./assets/img/Menu%20Utama.webp",
    "integrity": "sha256-ZkYLX9X7QGxqfd3T7hYGtFX2Hr+Ut6PyW08GuqK8/68=",
    "bytes": 963910
  },
  {
    "url": "./assets/img/PSMD/table1.png",
    "integrity": "sha256-+6Auk3f7SZkWygTkGg1xdMTMENw9+NUJZ3aPWeVveFw=",
    "bytes": 775341
  },
  {
    "url": "./assets/img/PSMD/table2.png",
    "integrity": "sha256-MBLin5T+93ftyQJo8qJdoGgpiujCvHq6IRMsMvSDh+w=",
    "bytes": 786819
  },
  {
    "url": "./assets/img/PSMD/table3.png",
    "integrity": "sha256-UsACJZ2FLQx0g4YcDsp9/vyBNzOgSsQ6iepib+O1Jfo=",
    "bytes": 768510
  },
  {
    "url": "./assets/img/PSPD/table.png",
    "integrity": "sha256-pASVEJRUjci42Rd6eEQlqUoXSGU134tQn4JfHmiZLGU=",
    "bytes": 788289
  },
  {
    "url": "./assets/img/RAS/Graph.png",
    "integrity": "sha256-nJbYs4qZTwyJnJ5R4WWXZfrzCm6lof0wfpfJMEL+JOI=",
    "bytes": 1134713
  },
  {
    "url": "./assets/img/RAS/Table.png",
    "integrity": "sha256-yKzl0nQ/EwS8UAaICJUAQWCzC0BXRlQFxhTJkDm2w+Y=",
    "bytes": 679296
  },
  {
    "url": "./assets/img/RMCD/table.png",
    "integrity": "sha256-trxDEappGevQ9jgBpQSFU85usyuw3k6/H7gKd2O01+M=",
    "bytes": 274923
  },
  {
    "url": "./assets/img/SRBS/illus-1.png",
    "integrity": "sha256-99sW/w4zYjlmjcoBKHNreSdEyBXwOE1OlmnCVIa+Uec=",
    "bytes": 61749
  },
  {
    "url": "./assets/img/SRBS/illus-2.png",
    "integrity": "sha256-P7U/CAsU6vRWt7zl8TBHPUJ4kGcAehfKpD5GJxj0miM=",
    "bytes": 671082
  },
  {
    "url": "./assets/img/SRS/CG.png",
    "integrity": "sha256-GjMUAz0gZj75FqotSC41XRV0iT9klMKOrdYXP4rSnDI=",
    "bytes": 132275
  },
  {
    "url": "./assets/img/SRS/MF.png",
    "integrity": "sha256-MKvoIUxLkbrRzjJD0lE7nREYxyEqHiToUz8pd95cBh4=",
    "bytes": 232496
  },
  {
    "url": "./assets/img/SRS/OAP.png",
    "integrity": "sha256-IRCBvCMOfA5K7OnVbeGcsT1YNMCnH3nMLtQrriVmhiU=",
    "bytes": 117098
  },
  {
    "url": "./assets/img/SRS/SLA.png",
    "integrity": "sha256-J1ijjMbbszzrihHOLTPL6Hj/LycYtYuV/aklsgGqKws=",
    "bytes": 108878
  },
  {
    "url": "./assets/img/SRS/sub-title.png",
    "integrity": "sha256-HgSDHepzqRnWN0Q8pB3xOAIR6vKvnugx8R8c0IKn1ik=",
    "bytes": 17966
  },
  {
    "url": "./assets/img/Sub%20Menu.webp",
    "integrity": "sha256-mIvcwIzES2RCHoe6PrfTyb+cEpQZowtOjFeMJCmvOhU=",
    "bytes": 5925258
  },
  {
    "url": "./assets/img/TMOI/Monetary%20Operation.png",
    "integrity": "sha256-EZKJpBpsFhrAgcFZsSe0W2ErjcVp7SKolTvALj+tWLs=",
    "bytes": 168084
  },
  {
    "url": "./assets/img/TNTSS/TNTSS.png",
    "integrity": "sha256-c32muRWYa8XCO95R3Yqyd2WbXjzgMVJwqDze68MZmQM=",
    "bytes": 199420
  },
  {
    "url": "./assets/img/arrow-left-gold.svg",
    "integrity": "sha256-AB8EQzqjVbvIEzv5LHux7X+/yr1BI/Xn/1Y929xm3OU=",
    "bytes": 24252
  },
  {
    "url": "./assets/img/arrow-right-gold.svg",
    "integrity": "sha256-YDjmNOnl+D9V9QrQIyHcGES6ddBL7vgClYAu5Een4yI=",
    "bytes": 24172
  },
  {
    "url": "./assets/img/arrow-white.png",
    "integrity": "sha256-eCpgWWJl37c16E1TiqPY06FLY12IEZArWi0TbvHsKMU=",
    "bytes": 7777
  },
  {
    "url": "./assets/img/bank-segi-lima.png",
    "integrity": "sha256-+EHe413H3FaEDEYdh2lCGgLpfgVmZUQz3XT+hG9LiC8=",
    "bytes": 407931
  },
  {
    "url": "./assets/img/bank-segi-lima.svg",
    "integrity": "sha256-eL4bjhDLHLZD1HrCBZztosp2osdgmMgnfWVdX02ThWA=",
    "bytes": 3845507
  },
  {
    "url": "./assets/img/btn-bg-center.png",
    "integrity": "sha256-UNn+g1L8fEnZ/iG+0uyPUJEQa/D2BXJLheX6u3Or3TM=",
    "bytes": 4279
  },
  {
    "url": "./assets/img/button-bg-blue.png",
    "integrity": "sha256-IoPCPOxtVYFCcajyHmKKC2xZp/XRkp233BGKWk93alQ=",
    "bytes": 5018
  },
  {
    "url": "./assets/img/giphy.gif",
    "integrity": "sha256-8kg4h175zsFLDDKBLf0k3mEAcfPityzC+/CRloJrQt4=",
    "bytes": 5050960
  },
  {
    "url": "./assets/img/qr-code.png",
    "integrity": "sha256-0ih4rtveftcqKTnE7lyp4le6qy2eYaDLt4iq8UAJ7pY=",
    "bytes": 36448
  },
  {
    "url": "./assets/img/segi-lima.svg",
    "integrity": "sha256-h1B+ZCMfe4hr3ICsoMg7I2cyzSZwbak0DYWt4FqwMbY=",
    "bytes": 54469
  },
  {
    "url": "./assets/js/components/back-button.js",
    "integrity": "sha256-JJ2MeV2gRJnKad9wNTA/u6Z2HNAiTpslJiRO2czPKGU=",
    "bytes": 1734
  },
  {
    "url": "./assets/js/components/button.js",
    "integrity": "sha256-Ke6oMqoJ2qz6vjbD3qBsKJUkVSbmwHLRy6zmWOR6Vnc=",
    "bytes": 2942
  },
  {
    "url": "./assets/js/components/card.js",
    "integrity": "sha256-+z84fsHLEEqGnsBNb5JgJQuHWN6hv4jKU8m36lpLkIY=",
    "bytes": 3122
  },
  {
    "url": "./assets/js/data/home.js",
    "integrity": "sha256-M3G2SB9BIloTFjfD80auR/sqy19NVzbQnzQ7SWZ2oBc=",
    "bytes": 985
  },
  {
    "url": "./assets/js/data/layanan-kebanksentralan.js",
    "integrity": "sha256-CZjiaUQMGRsuvPbdn68WtEZJSo3sF5Cx1K6TqWkJEQs=",
    "bytes": 4275
  },
  {
    "url": "./assets/js/data/layanan-kebanksentralan/CAABP.js",
    "integrity": "sha256-1hSD+HIPsblbaOxdhriomA3UxUZPsP5jyyfmUM3NxtI=",
    "bytes": 3913
  },
  {
    "url": "./assets/js/data/layanan-kebanksentralan/CAS.js",
    "integrity": "sha256-r/R4HqmCkxS0xUSzOBpL+NMUgdIWdIfJ6K/EzrUflhg=",
    "bytes": 2080
  },
  {
    "url": "./assets/js/data/layanan-kebanksentralan/LCIBP.js",
    "integrity": "sha256-ayDnDnsNtCckW5CXcAUDK61FnQ42wZUf36hY40x3LOM=",
    "bytes": 3828
  },
  {
    "url": "./assets/js/data/layanan-kebanksentralan/LCTS.js",
    "integrity": "sha256-mgVvHffsTD1p648pzM7CLiLWcpNoLSg5PwVlUDT3/hc=",
    "bytes": 2071
  },
  {
    "url": "./assets/js/data/layanan-kebanksentralan/SRBS.js",
    "integrity": "sha256-iUfu4VOeAEv5LQ5j7kBeDjEcwXlxisHYaHBQmkcb2SA=",
    "bytes": 3541
  },
  {
    "url": "./assets/js/data/layanan-kebanksentralan/SRS.js",
    "integrity": "sha256-0PGc1FbjxuRUvAg8igYdiPhk0WBdzeHJM9nXeNo4NF8=",
    "bytes": 3848
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/GM.js",
    "integrity": "sha256-OShjqwqDGfHN265b074kfmXmCZ5lpHjdyx00X651YpQ=",
    "bytes": 2734
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/MODRMO.js",
    "integrity": "sha256-lgrRBgif7VJEA7ZhpSLMgY9J5FE0MSYmIIwVG+UoYss=",
    "bytes": 2825
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/RAS.js",
    "integrity": "sha256-6hZ1/C5eF+W4G7uZ7DM59BEDBDrIGY/7W93MnwCaupo=",
    "bytes": 1709
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/SFTS.js",
    "integrity": "sha256-YuMGOQqI+Kq2yp+b0WPJb6Eap4gTASNpxVY34C5ddEE=",
    "bytes": 5009
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/SNTS.js",
    "integrity": "sha256-uC5d3prZYBVr9WeDvf5mmdWH/3wwzoV/LqdWk5HHtV0=",
    "bytes": 2648
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/SPS.js",
    "integrity": "sha256-jveoqpmQAnlgZH4u5fhoExkOhZ9ViqikqOM9Sdw9Upk=",
    "bytes": 3939
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/SRTS.js",
    "integrity": "sha256-/MsGZQQ8LPMVDQWvSzBfBloUD0NwnN7y+buT/gMNiik=",
    "bytes": 5046
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/TMOI.js",
    "integrity": "sha256-WsENPxhwZSDqnEoA+KfhswMTANcYtwZ7R5dQVD2Lde4=",
    "bytes": 1600
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/TNTSS.js",
    "integrity": "sha256-GuBT53VJmxeE2s1B5rMTS4oyxQVRorhevXM+0RBDCJI=",
    "bytes": 1564
  },
  {
    "url": "./assets/js/data/layanan-operasional-tresuri/profile.js",
    "integrity": "sha256-BMvbr64QfMusTGqVjuPiH8sgZ4yIAaYgb/zgdiUfPJ8=",
    "bytes": 3597
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/BSLAT1.js",
    "integrity": "sha256-KqlZyPlqpFzV5d4qcBCqiUYYxQU//Hw1dbdMBCHYhqc=",
    "bytes": 1666
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/BSLAT2.js",
    "integrity": "sha256-41FQ+ZbUwR18FvHIy7sgGgkR47wfzde2HRnM4+R/EFk=",
    "bytes": 1666
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/BSLAT3.js",
    "integrity": "sha256-6lAkbU570AbefHqCrATVzJtbEPHlOP/W82pEldsWACU=",
    "bytes": 1695
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/CMD1.js",
    "integrity": "sha256-WyhXhqzYtHztSelGcZvzi+1r4dslUyhEZsOlSFLlg/g=",
    "bytes": 1626
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/CMD2.js",
    "integrity": "sha256-EC8ETxbSXRv4AW2j1sFvkz2HDj5OgnYY0e9VCd2x/aM=",
    "bytes": 1628
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/CMD3.js",
    "integrity": "sha256-7ypuGzy7E3KZW4iIIAOZXNUhqdv7NlVH7RV76xA7KMc=",
    "bytes": 1628
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/ETIBI.js",
    "integrity": "sha256-YVmn5bRzj/FxWMqgBaoirQZIY1dHWA1DbWSiGXyDSbk=",
    "bytes": 5835
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/FMDD.js",
    "integrity": "sha256-ufZFfewHsDLTCBFIUoDXjZmZmQxLsvSxJV3Q/Bz8kb0=",
    "bytes": 4239
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/FMDD1.js",
    "integrity": "sha256-JU1kTkiOQgNIyqHPxhr1e4W/cimZX0wx7yfynfeWoqU=",
    "bytes": 1640
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/FMDD2.js",
    "integrity": "sha256-zx9o3k1HoFu0dQVjO4AMdBcpHkne9fomPgyU2orbKJg=",
    "bytes": 1640
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/FMDD3.js",
    "integrity": "sha256-k0Xxwe77SL1z5FGfcmRhTclvjsDgMHfcnDCHv7tNL0c=",
    "bytes": 1640
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/FMDD4.js",
    "integrity": "sha256-4UbWFN0mmEY0EPGCehN4lfWk1Wkk5IOBc4I/JBSJROA=",
    "bytes": 1640
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/FMDD5.js",
    "integrity": "sha256-eD53bxrRwzg7LwqHfMLnNDxWEL46acf7c4EUx7C8CSg=",
    "bytes": 1641
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/IEFD.js",
    "integrity": "sha256-5WPdM9wIVmnYQms+nP0i0a41GdxAct5sh6Gm/EdK/iw=",
    "bytes": 1683
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/LF.js",
    "integrity": "sha256-8C58cWEiETCPlm9wIygX42axLTZfxd9EVU0o/E7GSKY=",
    "bytes": 1768
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/MASMD.js",
    "integrity": "sha256-p+zeFohJlCuVuD7oSbK7jYuaJWoiPheKidyiVr9wY84=",
    "bytes": 3488
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/MASMD2.js",
    "integrity": "sha256-VQpEjWFyWwBJXVHR8GvAEifApgyGxpSy9ewun+q95pU=",
    "bytes": 1680
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/MMAMSD.js",
    "integrity": "sha256-VyJiSzxS5Jf9DRntpxYZUeFAoQAJrJYk4dLBQbSUOg4=",
    "bytes": 1688
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/PSMD1.js",
    "integrity": "sha256-w9YN/prDUBU7fMV3Jm39RR1aKMokp5XS0bbhu9GLyW0=",
    "bytes": 1637
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/PSMD2.js",
    "integrity": "sha256-0yJef4Ze23lolFmarnqRC38A4AjouyD6FvZ6ET7wUJs=",
    "bytes": 1637
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/PSMD3.js",
    "integrity": "sha256-y9AoVuNSpA1yN0+KSvyPKEBejiRNjIevCoDdzPkTuM8=",
    "bytes": 1676
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/PSPD.js",
    "integrity": "sha256-ueNUYM6KX50ZEv+lDA6Of/AeLhcsN4i0mR/zyShfOno=",
    "bytes": 1629
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/RMCD.js",
    "integrity": "sha256-mSUw20kw5ZFS+fSyhDy2x1/YYmb33zv90lsgFg9GpWc=",
    "bytes": 1296
  },
  {
    "url": "./assets/js/data/perizinan-terpadu/integrated-licensing.js",
    "integrity": "sha256-96HmMcYhjRkg6wx7dBnDaPoAo5On7UT8es13LX2UshY=",
    "bytes": 1359
  },
  {
    "url": "./assets/js/data/quiz/quiz.js",
    "integrity": "sha256-4333zrzO9mSugHxBmmcQsh03T1pze3EOYM167e6WZUE=",
    "bytes": 31277
  },
  {
    "url": "./assets/js/init.js",
    "integrity": "sha256-089TgRzX27PwUyVBfdwkEWLt4m5d9zMQeSX4ayJ4ZHo=",
    "bytes": 215
  },
  {
    "url": "./assets/js/jquery.js",
    "integrity": "sha256-PnUB0Vw2MOeRyLIDkuud7jGp9lzj793nbO9ccQFBqyQ=",
    "bytes": 87532
  },
  {
    "url": "./assets/js/lib.min.js",
    "integrity": "sha256-Lfgh4c+xY/FqajT28Omn4hGTf0DE/vxSLDekfNrGA8M=",
    "bytes": 259717
  },
  {
    "url": "./assets/js/offline.js",
    "integrity": "sha256-KRlIX36XEL5nuP27aq5b+l5z2SBP+RvqOfF0DiuQsxM=",
    "bytes": 3770
  },
  {
    "url": "./assets/videos/MENU%20UTAMA.mp4",
    "integrity": "sha256-govPAA0HHQYyz28wEGk4NZQUSaaJGf4POZ6RIwmXQw0=",
    "bytes": 13795883
  },
  {
    "url": "./assets/videos/SAVE%20SCREEN.mp4",
    "integrity": "sha256-Y7gQVnVoJkGY8prIIqJhoApdJf1m5c1hHKsZkJ+v5sA=",
    "bytes": 13876893
  },
  {
    "url": "./assets/videos/SUB%20MENU.mp4",
    "integrity": "sha256-ByEeV0eMuQTjV38qCN2ZUKOxDeKWgaOVOUXpR4utx0Y=",
    "bytes": 14072121
  },
  {
    "url": "./data.json",
    "integrity": "sha256-OdB9D0sBoMPBelcoWppHJcExO6LFcTdScCC1XChYOks=",
    "bytes": 14
  },
  {
    "url": "./index.html",
    "integrity": "sha256-tH/rkGdO/+RW6lFnQ13aU9XRapE8PuZ4MV4iQnhFoYI=",
    "bytes": 21401
  }
];
// VERSION and ASSETS are inserted by the generator.
const PREFIX = `cbfest:${self.registration.scope}:`;
const CACHE = PREFIX + VERSION;
const absolute = path => new URL(path, self.registration.scope).href;
const INDEX = absolute('./index.html');
const URLS = new Set(ASSETS.map(asset => absolute(asset.url)));
let progress = null;

async function broadcast(message) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' });
  clients.filter(client => client.url.startsWith(self.registration.scope))
    .forEach(client => client.postMessage({ type: 'BOOTH_CACHE', ...message }));
}

let preparing;
function prepareCache() {
  if (preparing) return preparing;
  preparing = (async () => {
    const cache = await caches.open(CACHE);
    const queue = [...ASSETS];
    progress = { state: 'downloading', completed: 0, total: ASSETS.length };
    let failure;
    // Limit concurrent downloads; retain verified partial downloads for retries.
    await Promise.all(Array.from({ length: 4 }, async () => {
      while (queue.length && !failure) {
        const asset = queue.shift();
        try {
          const url = absolute(asset.url);
          if (!await cache.match(url)) {
            const response = await fetch(new Request(url, {
              cache: 'reload', integrity: asset.integrity, credentials: 'same-origin',
            }));
            if (!response.ok || response.status === 206) throw new Error(`HTTP ${response.status}: ${asset.url}`);
            await cache.put(url, response);
          }
          progress.completed++;
          await broadcast(progress);
        } catch (error) {
          failure = error;
        }
      }
    }));
    if (failure) {
      progress = { state: 'error' };
      await broadcast(progress);
      throw failure;
    }
    // Updates wait until all old tabs close, avoiding mixed versions during a game.
    progress = { state: 'installed' };
    await broadcast(progress);
  })().finally(() => { preparing = null; });
  return preparing;
}

self.addEventListener('install', event => {
  event.waitUntil(prepareCache());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith(PREFIX) && name !== CACHE)
      .map(name => caches.delete(name)));
    await self.clients.claim();
    await broadcast({ state: 'ready' });
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type === 'BOOTH_CACHE_REPAIR') {
    event.waitUntil(prepareCache().then(() => broadcast({ state: 'ready' })).catch(() => {}));
    return;
  }
  if (event.data?.type !== 'BOOTH_CACHE_STATUS') return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const keys = new Set((await cache.keys()).map(request => request.url));
    const complete = [...URLS].every(url => keys.has(url));
    event.source?.postMessage({
      type: 'BOOTH_CACHE',
      ...(complete ? { state: 'ready' } : progress?.state === 'downloading' ? progress : { state: 'error' }),
    });
  })());
});

async function rangedResponse(response, range) {
  const blob = await response.blob();
  const match = /^bytes=(\d*)-(\d*)$/.exec(range);
  // Unsupported multipart ranges can legally receive the entire representation.
  if (!match || (!match[1] && !match[2])) return new Response(blob, { headers: response.headers });
  const size = blob.size;
  const start = match[1] ? Number(match[1]) : Math.max(0, size - Number(match[2]));
  const end = match[1] && match[2] ? Math.min(Number(match[2]), size - 1) : size - 1;
  if (start >= size || start > end) {
    return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}` } });
  }
  const headers = new Headers(response.headers);
  headers.delete('Content-Encoding');
  headers.set('Accept-Ranges', 'bytes');
  headers.set('Content-Range', `bytes ${start}-${end}/${size}`);
  headers.set('Content-Length', String(end - start + 1));
  return new Response(blob.slice(start, end + 1), { status: 206, headers });
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  const home = absolute('./');
  const cleanURL = url.origin + url.pathname;
  const isPage = request.mode === 'navigate' && (cleanURL === home || cleanURL === INDEX);
  if (!isPage && !URLS.has(cleanURL)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(isPage ? INDEX : cleanURL);
    if (cached) {
      const range = request.headers.get('Range');
      return range ? rangedResponse(cached, range) : cached;
    }
    // Never turn an uncached image/API/unknown route into an HTML response.
    return fetch(request);
  })());
});
