import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
async function walk(directory) {
  const entries = await readdir(path.join(root, directory), { withFileTypes: true });
  const groups = await Promise.all(entries.filter(e => !e.name.startsWith('.')).map(e => {
    const name = `${directory}/${e.name}`;
    return e.isDirectory() ? walk(name) : [name];
  }));
  return groups.flat();
}
const files = ['index.html', 'data.json', ...await walk('assets')].sort();
const manifest = await Promise.all(files.map(async file => {
  const body = await readFile(path.join(root, file));
  return {
    url: './' + file.split('/').map(encodeURIComponent).join('/'),
    integrity: 'sha256-' + createHash('sha256').update(body).digest('base64'),
    bytes: body.length,
  };
}));
const template = await readFile(path.join(root, 'scripts/sw-template.js'), 'utf8');
const version = createHash('sha256').update(JSON.stringify(manifest) + template).digest('hex').slice(0, 16);
const output = '// Generated by node scripts/build-offline.mjs. Do not edit directly.\n' +
  `const VERSION = ${JSON.stringify(version)};\nconst ASSETS = ${JSON.stringify(manifest, null, 2)};\n` + template;
const destination = path.join(root, 'sw.js');
if (process.argv.includes('--check')) {
  if (await readFile(destination, 'utf8').catch(() => '') !== output) {
    throw new Error('sw.js belum diperbarui. Jalankan node scripts/build-offline.mjs sebelum deploy.');
  }
} else {
  await writeFile(destination, output);
}
console.log(`Offline ${version}: ${files.length} files, ${(manifest.reduce((n, a) => n + a.bytes, 0) / 1024 / 1024).toFixed(1)} MiB`);
